name: Publish Package

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build
        run: ./gradlew build

      - name: Build Artifacts
        run: ./gradlew assembleRelease androidSourcesJar

      - name: Create secrets file
        env:
          MAVEN_PGP_KEY_BASE64_CONTENT: ${{ secrets.MAVEN_PGP_KEY_BASE64_CONTENT }}
          MAVEN_PGP_KEY: ${{ secrets.MAVEN_PGP_KEY }}
        run: sudo bash -c "echo '$MAVEN_PGP_KEY_BASE64_CONTENT' | base64 -d > '$MAVEN_PGP_KEY'"

      - name: Publish to Maven Central
        env:
          MAVEN_OSS_PASSWORD: ${{ secrets.MAVEN_OSS_PASSWORD }}
          MAVEN_OSS_USERNAME: ${{ secrets.MAVEN_OSS_USERNAME }}
          MAVEN_PGP_KEY: ${{ secrets.MAVEN_PGP_KEY }}
          MAVEN_PGP_KEY_ID: ${{ secrets.MAVEN_PGP_KEY_ID }}
          MAVEN_PGP_KEY_PASSWORD: ${{ secrets.MAVEN_PGP_KEY_PASSWORD }}
          MAVEN_STAGING_PROFILE_ID: ${{ secrets.MAVEN_STAGING_PROFILE_ID }}
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        
